mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
]

mysite/polls/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from .views import create_question_and_choices, QuestionDeleteView

app_name = 'polls'
urlpatterns = [
    # path('', views.index, name='index'),
    #
    # path('<int:question_id>/', views.detail, name='detail'),
    #
    # path('<int:question_id>/results/', views.results, name='results'),
    #
    # path('<int:question_id>/vote/', views.vote, name='vote'),
    path('', views.IndexView.as_view(), name='polls-home'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='polls/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='polls/logout.html'), name='logout'),
    path('question/create/', create_question_and_choices, name='question-create'),
    path('question/<int:pk>/edit/', create_question_and_choices, name='question-edit'),
    path('question/<int:pk>/delete/', QuestionDeleteView.as_view(), name='question-delete'),
    # path( 'url(r'^simpleemail/(?P<emailto>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/', 'sendSimpleEmail' , name = 'sendSimpleEmail'),)
]

mysite/polls/models.py
import datetime

from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    questioner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        return reverse('polls:polls-home')

    def was_published_recently(self):
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

from .models import Question, Choice


from django.contrib.auth.forms import UserCreationForm



class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

# class DateInput(forms.DateInput):
#     input_type = 'date'
#
#
class QuestionForm(ModelForm):

    class Meta:
        model = Question
        fields = ['question_text', 'pub_date']


class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']

mysite/polls/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponseForbidden

from .models import Question, Choice
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required

from .forms import UserRegisterForm, QuestionForm, ChoiceForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = UserRegisterForm()
    return render(request, 'polls/register.html', {'form': form})

class IndexView(generic.ListView):
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # # output = ', '.join([q.question_text for q in latest_question_list])
    # context = {'latestposts': latest_question_list}
    # return render(request, 'polls/index.html', context)

    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'      # for ListView, the automatically generated context variable is question_list.

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')

class DetailView(generic.DetailView):
    # question = get_object_or_404(Question, pk=question_id)
    # return render(request, 'polls/detail.html', {'question':question})

    model = Question
    template_name = 'polls/detail.html'


    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    # question = get_object_or_404(Question, pk=question_id)
    # return render(request, 'polls/results.html', {'question': question})

    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choices.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

# class QuestionCreateView(LoginRequiredMixin, generic.CreateView):
#     model = Question
#     fields = ['question_text', 'pub_date']
#
#
#     def form_valid(self, form):
#         form.instance.questioner = self.request.user
#         return super().form_valid(form)




@login_required()
def create_question_and_choices_single_choice(request, pk=None):

    q_obj = Question.objects.get(id=pk) if pk else Question()
    if pk is None or q_obj.questioner == request.user:
        c_obj = q_obj.choices.first() if pk else Choice()
        if request.method == 'POST':
            q_form = QuestionForm(data=request.POST, instance=q_obj)
            c_form = ChoiceForm(data=request.POST, instance=c_obj)
            if q_form.is_valid() and c_form.is_valid():
                q_obj = q_form.save(commit=False)
                q_obj.questioner = request.user
                q_obj.save()

                c_obj = c_form.save(commit=False)
                c_obj.question = q_obj
                c_obj.save()
                return redirect('polls:polls-home')
        else:
            q_form = QuestionForm(instance=q_obj)
            c_form = ChoiceForm(instance=c_obj)

        context = {
            'q_form': q_form,
            'c_form': c_form}
        return render(request, 'polls/question_form.html', context)
    else:
        # return HttpResponseForbidden()
        raise PermissionDenied



from django.forms import formset_factory, inlineformset_factory
@login_required()
def create_question_and_choices(request, pk=None):
    q_obj = Question.objects.get(id=pk) if pk else Question()
    if pk is None or q_obj.questioner == request.user:
        ChoiceFormSet = inlineformset_factory(Question, Choice, fields=('choice_text',), extra=0 if pk else 1)

        if request.method == 'POST':
            q_form = QuestionForm(data=request.POST, instance=q_obj)
            if pk:
                c_forms = ChoiceFormSet(request.POST, instance=q_obj)
            else:
                c_forms = ChoiceFormSet(request.POST)

            if q_form.is_valid() and c_forms.is_valid():
                q_obj = q_form.save(commit=False)
                q_obj.questioner = request.user
                q_obj.save()

                if not pk:
                    c_forms.instance = q_obj

                c_forms.save()

                return redirect('polls:polls-home')
        else:
            q_form = QuestionForm(instance=q_obj)
            c_forms = ChoiceFormSet(instance=q_obj if pk else None)

        context = {
            'q_form': q_form,
            'c_forms': c_forms}
        return render(request, 'polls/question_form.html', context)
    else:
        # return HttpResponseForbidden()
        raise PermissionDenied


class QuestionDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Question
    success_url = '/'

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.questioner:
            return True
        return False

mysite/polls/templates/polls/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Polls-App</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.0.min.js" ></script>
    <script type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</head>
<body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <span class="navbar-nav text-white margin-left-50 " style="font-size:larger">Ankit's Polling System</span>
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
        <li class="nav-item">
          <span class="nav-link text-white">Welcome {{ user }}</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'polls:polls-home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'polls:question-create' %}">Create Poll</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'polls:logout' %}">Sign Out</a>
        </li>
          {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'polls:polls-home' %}">Home</a>
        </li>
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="{% url 'polls:login' %}">Create Poll</a>#}
{#        </li>#}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'polls:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'polls:login' %}">Sign In</a>
        </li>
        {% endif %}
      </ul>

    </nav>

    {% block content %}
    {% endblock content %}
</body>
</html>

mysite/polls/templates/polls/detail.html
{% extends "polls/basic.html" %}
{% block content %}

<!--    <h1>{{ question.question_text }}</h1>-->
<!--    <ul>-->
<!--    {% for choice in question.choice_set.all %}-->
<!--        <li>{{ choice.choice_text }}</li>-->
<!--    {% endfor %}-->
<!--    </ul>-->
<!--    -->
<!--    -->

    <div class = 'content-section'>
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choices.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
    </form>
    </div>
{% endblock content %}

mysite/polls/templates/polls/index.html
{% extends "polls/basic.html" %}
{% block content %}


    <div class = "list-question">
    {% if latest_question_list %}
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Poll ID</th>
              <th scope="col">Poll Question</th>
              <th scope="col">Published On</th>
              <th scope="col">Vote</th>
              <th scope="col">Results</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for question in latest_question_list %}
            <tr>
              <th scope="row">{{ question.id }}</th>
              <td>{{ question.question_text }}</td>
              <td>{{ question.pub_date }}</td>
              <td><a class="" href="{% url 'polls:detail' question.id %}">Vote</a></td>
              <td>
                  {% for choice in question.choices.all %}
                    {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} <br>
                  {% endfor %}
              </td>
              <td>
                {% if question.questioner == user %}
                  <a href="{% url 'polls:question-edit' question.id %}" >Edit</a>
                  <a  href="{% url 'polls:question-delete' question.id %}">Delete</a>
                {% else %}
                  <a title="Only poll owner can perform this action" class="text-grey">Edit</a>
                  <a title="Only poll owner can perform this action" class="text-grey">Delete</a>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    </div>

{% endblock content %}

{##}
{#{% load static %}#}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">#}
{#    <title>Polls-App</title>#}
{##}
{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">#}
{#    <!-- jQuery first, then Popper.js, then Bootstrap JS -->#}
{#    <script src="https://code.jquery.com/jquery-3.5.0.min.js" ></script>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>#}
{#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>#}
{##}
{#</head>#}
{#<body>#}
{#    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">#}
{##}
{#      <ul class="navbar-nav ">#}
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="{% url 'polls:register' %}">Register</a>#}
{#        </li>#}
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="{% url 'polls:login' %}">LogIn</a>#}
{#        </li>#}
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="{% url 'polls:logout' %}">LogOut</a>#}
{#        </li>#}
{#      </ul>#}
{##}
{#    </nav>#}
{#        <div class = "list-question">#}
{#    {% if latest_question_list %}#}
{#        <ul>#}
{#        {% for question in latest_question_list %}#}
{#            <li><a class="list-group-item list-group-item-action" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>#}
{#        {% endfor %}#}
{#        </ul>#}
{#    {% else %}#}
{#        <p>No polls are available.</p>#}
{#    {% endif %}#}
{#    </div>#}
{##}
{##}
{#</body>#}
{#</html>#}

mysite/polls/templates/polls/login.html
{% extends "polls/basic.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'polls:register' %}">Register Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

mysite/polls/templates/polls/logout.html
{% extends "polls/basic.html" %}
{% block content %}
    <div style="margin:70px">
        You have been logged out.
        <div>
            <a href="{% url 'polls:login' %}">Log In Again</a>
        </div>
    </div>
{% endblock content %}

mysite/polls/templates/polls/question_confirm_delete.html
{% extends "polls/basic.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Question</legend>
                <h2>Are you sure you want to delete the question "{{ object.question_text}}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'polls:polls-home'  %}">Cancel</a>
            </div>
        </form>
    </div>

{% endblock content %}

mysite/polls/templates/polls/question_form.html
<script src="https://raw.githubusercontent.com/elo80ka/django-dynamic-formset/master/src/jquery.formset.js"></script>

{% extends "polls/basic.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Polls Question</legend>
                {{ q_form|crispy }}

                {{ c_forms.management_form }}
                {% for c in c_forms %}
{#                    {{ c.id }}#}
{#                    {% for hidden in c.hidden_fields %}#}
{#                        {{ hidden }}#}
{#                    {% endfor %}#}
                <div class="inline {{ c_forms.prefix }}">
                  {{ c|crispy }}
                </div>
                {% endfor %}

            </fieldset>
        <script type="text/javascript">
            $(".inline.{{ c_forms.prefix }}").formset({
            prefix: "{{ c_forms.prefix }}",
            //formCssClass: 'dynamic-formset1',
            addText: 'Add Choice',
            deleteText: 'Remove Choice'
        });
        </script>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>

{% endblock content %}

mysite/polls/templates/polls/register.html
{% extends "polls/basic.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'polls:login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}

mysite/polls/templates/polls/results.html
{% extends "polls/basic.html" %}
{% block content %}
    <div class="content-section">
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choices.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
    </div>
{% endblock content %}